# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/data-science-notes',
                'doc_host': 'https://HenryDashwood.github.io',
                'git_url': 'https://github.com/HenryDashwood/data-science-notes',
                'lib_path': 'data_science_notes'},
  'syms': {'data_science_notes.core': {'data_science_notes.core.foo': ('core.html#foo', 'data_science_notes/core.py')}}}
